import assert from "node:assert/strict";
import {
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";

import {
  normalizeLinuxDebianArtifactNames,
  tauriLinuxDebianArtifactName,
  validateTauriDebianArtifactEntries,
} from "./linux-debian-artifact-identity.mjs";

test("derives the Tauri filename from the technical Linux product identity", () => {
  assert.equal(tauriLinuxDebianArtifactName("0.1.0"), "fitfreed_0.1.0_amd64.deb");
  assert.throws(() => tauriLinuxDebianArtifactName("../0.1.0"), /invalid package version/);
});

test("renames an unsigned Tauri package without changing its bytes", () => {
  const directory = mkdtempSync(path.join(tmpdir(), "fitfreed-debian-artifact-"));
  const generated = path.join(directory, "fitfreed_0.1.0_amd64.deb");
  const bytes = Buffer.from("synthetic unchanged Debian package bytes");
  writeFileSync(generated, bytes);
  try {
    const result = normalizeLinuxDebianArtifactNames({ directory, version: "0.1.0" });
    assert.deepEqual(result, {
      packagePath: path.join(directory, "FitFreed_0.1.0_amd64.deb"),
      signaturePath: undefined,
    });
    assert.deepEqual(readFileSync(result.packagePath), bytes);
    assert.deepEqual(readdirSync(directory), ["FitFreed_0.1.0_amd64.deb"]);
  } finally {
    rmSync(directory, { recursive: true, force: true });
  }
});

test("renames a required updater signature with its unchanged signed package", () => {
  const directory = mkdtempSync(path.join(tmpdir(), "fitfreed-signed-debian-artifact-"));
  const generated = path.join(directory, "fitfreed_0.1.0_amd64.deb");
  const signature = `${generated}.sig`;
  writeFileSync(generated, "signed package bytes");
  writeFileSync(signature, "detached updater signature");
  try {
    const result = normalizeLinuxDebianArtifactNames({
      directory,
      signature: "required",
      version: "0.1.0",
    });
    assert.equal(readFileSync(result.packagePath, "utf8"), "signed package bytes");
    assert.equal(readFileSync(result.signaturePath, "utf8"), "detached updater signature");
    assert.deepEqual(readdirSync(directory).sort(), [
      "FitFreed_0.1.0_amd64.deb",
      "FitFreed_0.1.0_amd64.deb.sig",
    ]);
  } finally {
    rmSync(directory, { recursive: true, force: true });
  }
});

test("leaves generated bytes untouched when identity admission fails", () => {
  const directory = mkdtempSync(path.join(tmpdir(), "fitfreed-rejected-debian-artifact-"));
  const generated = path.join(directory, "fitfreed_0.1.0_amd64.deb");
  writeFileSync(generated, "original package");
  try {
    assert.throws(
      () => normalizeLinuxDebianArtifactNames({
        directory,
        signature: "required",
        version: "0.1.0",
      }),
      /required updater signature is missing/,
    );
    assert.equal(readFileSync(generated, "utf8"), "original package");

    writeFileSync(path.join(directory, "unexpected.deb"), "unexpected package");
    assert.throws(
      () => normalizeLinuxDebianArtifactNames({ directory, version: "0.1.0" }),
      /exactly the expected Tauri Debian artifact/,
    );
    assert.deepEqual(readdirSync(directory).sort(), [
      "fitfreed_0.1.0_amd64.deb",
      "unexpected.deb",
    ]);
  } finally {
    rmSync(directory, { recursive: true, force: true });
  }
});

test("admits only generated and replaceable canonical package outputs", () => {
  const entries = [
    { isFile: () => true, name: "fitfreed_0.1.0_amd64.deb" },
    { isFile: () => true, name: "FitFreed_0.1.0_amd64.deb" },
  ];
  assert.doesNotThrow(
    () => validateTauriDebianArtifactEntries(
      entries,
      "fitfreed_0.1.0_amd64.deb",
      "FitFreed_0.1.0_amd64.deb",
    ),
  );
  entries.push({ isFile: () => true, name: "unexpected.deb" });
  assert.throws(
    () => validateTauriDebianArtifactEntries(
      entries,
      "fitfreed_0.1.0_amd64.deb",
      "FitFreed_0.1.0_amd64.deb",
    ),
    /exactly the expected Tauri Debian artifact/,
  );
});
